<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="FirstSuite" duration-ms="12080" started-at="2013-07-16T05:56:57Z" finished-at="2013-07-16T05:57:09Z">
    <groups>
    </groups>
    <test name="FirstLoginDemoTest" duration-ms="12080" started-at="2013-07-16T05:56:57Z" finished-at="2013-07-16T05:57:09Z">
      <class name="com.hp.runner.DemoRun">
        <test-method status="PASS" signature="beforeSuite(java.lang.String, java.lang.String)[pri:0, instance:com.hp.runner.DemoRun@13bd574]" name="beforeSuite" is-config="true" duration-ms="4078" started-at="2013-07-16T13:56:53Z" finished-at="2013-07-16T13:56:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[resources/TestData.xls]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[localhost]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="SUCCESS_PERCENTAGE_FAILURE" signature="demoTest()[pri:0, instance:com.hp.runner.DemoRun@13bd574]" name="demoTest" duration-ms="3457" started-at="2013-07-16T13:56:57Z" finished-at="2013-07-16T13:57:01Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.hp.pop.DemoPage.demoTest(DemoPage.java:13)
	at com.hp.runner.DemoRun.demoTest(DemoRun.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoTest -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult, org.testng.ITestContext)[pri:0, instance:com.hp.runner.DemoRun@13bd574]" name="afterMethod" is-config="true" duration-ms="348" started-at="2013-07-16T13:57:01Z" finished-at="2013-07-16T13:57:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=demoTest status=SUCCESS WITHIN PERCENTAGE method=DemoRun.demoTest()[pri:0, instance:com.hp.runner.DemoRun@13bd574] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@2798e7]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="demoTest()[pri:0, instance:com.hp.runner.DemoRun@13bd574]" name="demoTest" duration-ms="1042" started-at="2013-07-16T13:57:02Z" finished-at="2013-07-16T13:57:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.hp.pop.DemoPage.demoTest(DemoPage.java:13)
	at com.hp.runner.DemoRun.demoTest(DemoRun.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoTest -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult, org.testng.ITestContext)[pri:0, instance:com.hp.runner.DemoRun@13bd574]" name="afterMethod" is-config="true" duration-ms="208" started-at="2013-07-16T13:57:03Z" finished-at="2013-07-16T13:57:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=demoTest status=FAILURE method=DemoRun.demoTest()[pri:0, instance:com.hp.runner.DemoRun@13bd574] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@2798e7]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="demoTest2()[pri:0, instance:com.hp.runner.DemoRun@13bd574]" name="demoTest2" duration-ms="6015" started-at="2013-07-16T13:57:03Z" finished-at="2013-07-16T13:57:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoTest2 -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult, org.testng.ITestContext)[pri:0, instance:com.hp.runner.DemoRun@13bd574]" name="afterMethod" is-config="true" duration-ms="1" started-at="2013-07-16T13:57:09Z" finished-at="2013-07-16T13:57:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=demoTest2 status=SUCCESS method=DemoRun.demoTest2()[pri:0, instance:com.hp.runner.DemoRun@13bd574] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@2798e7]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.hp.runner.DemoRun@13bd574]" name="afterSuite" is-config="true" duration-ms="1148" started-at="2013-07-16T13:57:09Z" finished-at="2013-07-16T13:57:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.hp.runner.DemoRun -->
    </test> <!-- FirstLoginDemoTest -->
  </suite> <!-- FirstSuite -->
</testng-results>
